footprint: [[-0.28,0.25],[0.28,0.25],[0.28,-0.25],[-0.28,-0.25]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 1.5

resolution: 0.04

obstacle_range: 5.0
raytrace_range: 6.0

#layer definitions

obstacles_laser:
  observation_sources: point_cloud_sensor
  point_cloud_sensor: {sensor_frame: laser, data_type: PointCloud2, topic: /velodyne_points, marking: true, clearing: true, min_obstacle_height: 0.2}
    
