global_frame: map
rolling_window: false
track_unknown_space: true

plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
  - {name: obstacle, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

update_frequency: 5.0
static_map: true
resolution: 0.05

inflation:
  inflation_radius: 0.6

static:
  map_topic: /map
  subscribe_to_updates: true